version: "3"

services:
  php:
    build:
      context: ./
      dockerfile: ./docker/php/Dockerfile
    container_name: php_container
    networks:
      - laravel-docker
    volumes:
      - ./:/var/www/laravel
    expose:
      - "9000"
    command: ["php-fpm"]
    env_file:
      - docker.env

  mysql:
    image: mysql:5.7
    container_name: mysql_container
    networks:
      - laravel-docker
    environment:
      - MYSQL_ROOT_PASSWORD=root
    expose:
      - "3309"
    ports:
      - "3309:3306"
    volumes:
      - ./docker-storage/mysql:/var/lib/mysql

  redis:
    image: redis:5-alpine
    container_name: redis_container
    networks:
      - laravel-docker
    ports:
      - "6376:6379"
    volumes:
      - ./docker-storage/redis:/data/db

  nginx:
    build:
      context: ./
      dockerfile: ./docker/nginx/Dockerfile
    container_name: nginx_container
    working_dir: /usr/share/nginx/laravel
    networks:
      - laravel-docker
    ports:
      - "8000:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www/laravel

networks:
  laravel-docker:
    driver: bridge
  